name: PDF Builder
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generating a single Markdown file
        run: cat 0*.md > Documentation.md
      - uses: lothindir/pandoc-markdown-action@v0.1
        with:
          markdown: "Documentation.md"
          pdf: "Documentation"
          template: "kate"
