name: PDF Builder
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing pandoc and TexLive
        run: |
          sudo apt-get update -y
          sudo apt-get upgrade -y
          sudo apt-get install texlive-full -y
          curl -L "https://github.com/jgm/pandoc/releases/download/2.16.2/pandoc-2.16.2-1-amd64.deb" -o pandoc.deb
          sudo dpkg -i pandoc.deb -y
      - name: Generating a PDF
        run: pandoc --defaults pandoc.yml
      - name: Saving Documentation.pdf as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: Documentation PDF
          path: Documentation.pdf
